version: '3.8'
services:
  app:
    container_name: ci-biolink
    build: 
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - db
  
  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cidb
      MYSQL_USER: luis
      MYSQL_PASSWORD: doggfather
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306